const body=document.body, header=document.getElementById('site-header'), progress=document.querySelector('.scroll-progress');
const themeToggle=document.getElementById('theme-toggle'), menuToggle=document.getElementById('menu-toggle'), navLinks=document.getElementById('nav-links');
const savedTheme=localStorage.getItem('ngf-theme'); if(savedTheme==='light') body.classList.add('light');
themeToggle?.addEventListener('click',()=>{body.classList.toggle('light');localStorage.setItem('ngf-theme',body.classList.contains('light')?'light':'dark')});
menuToggle?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open)});
navLinks?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false')}));
function scrollUI(){const y=window.scrollY;header.classList.toggle('scrolled',y>12);const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=(max>0?y/max*100:0)+'%'} window.addEventListener('scroll',scrollUI,{passive:true});scrollUI();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const sections=[...document.querySelectorAll('main section[id]')], nav=[...document.querySelectorAll('.nav-link')];
const activeObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){nav.forEach(n=>n.classList.toggle('active',n.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>activeObs.observe(s));
const statsObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return; e.target.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count), start=performance.now(), dur=1000; const tick=now=>{const p=Math.min((now-start)/dur,1), val=Math.round((1-Math.pow(1-p,3))*target);el.innerHTML=val+(target===100?'<small>%</small>':'');if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});statsObserver.unobserve(e.target)}),{threshold:.3});const stats=document.querySelector('.stats-section');if(stats)statsObserver.observe(stats);
// Real-photo guard: if an original uploaded asset is absent, show a clearly intentional fallback rather than a broken image.
document.querySelectorAll('.photo-wrap img').forEach(img=>img.addEventListener('error',()=>img.parentElement.classList.add('is-fallback')));
// Lightweight hero particle field.
const canvas=document.getElementById('particles');const ctx=canvas?.getContext('2d');let pts=[];function resizeCanvas(){if(!canvas)return;canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pts=Array.from({length:Math.min(65,Math.floor(innerWidth/20))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.3+.2,v:(Math.random()-.5)*.16}))}function draw(){if(!canvas)return;ctx.clearRect(0,0,innerWidth,innerHeight);const light=body.classList.contains('light');ctx.fillStyle=light?'rgba(99,102,241,.22)':'rgba(148,163,184,.22)';pts.forEach(p=>{p.y+=p.v;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}resizeCanvas();window.addEventListener('resize',resizeCanvas);draw();
document.getElementById('year').textContent=new Date().getFullYear();
